### ISSUE TITLE
FN ERROR

### ISSUE THREAD

**Issue by morelli690** [haram/watermark_disabler#1]
undefined FN https://github.com/haram/watermark_disabler/blob/cbb6100aa7585f12c132b1a611f9392768ee65b4/watermark_disabler/mem_scan.hpp#L11

+  +load it with OSR doesn't work, getting integrity checks fail(even with this disabled with bcedit)
+  +I made if work with manual mapping but it gives me BSOD when attempt to attach to csrss,
> impl::unique_attachment csrss_attach(csrss_process);//bsod here
+  +is it working for which version of windows? 
My discord: Cesar#3165 if u can msg me there

**Comment by gundamhyl** [comment]
#include <utility> ???
Missing some header files, how did you compile?

**Comment by gundamhyl** [comment]
#include <utility> ?
Missing some header files, how did you compile?

**Comment by gundamhyl** [comment]
#include <utility>
Missing some header files, how did you compile?

**Comment by gundamhyl** [comment]
Missing some header files, such as <utility>, how did you compile it?

**Comment by feeas** [comment]
Missing some header files, such as "utility", how did you compile it?

**Comment by morelli690** [comment]
i try debug and release.

**Comment by morelli690** [comment]
can you show/send me the missing header?
+ did u see the other issues?

**Comment by feeas** [comment]
https://github.com/haram/watermark_disabler/blob/cbb6100aa7585f12c132b1a611f9392768ee65b4/watermark_disabler/main.cpp#L1
https://github.com/haram/watermark_disabler/blob/cbb6100aa7585f12c132b1a611f9392768ee65b4/watermark_disabler/mem_util.hpp#L3

I can't find 2 header file, so I can't compile it.

**Comment by morelli690** [comment]
this project isnt yours?
